# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_ace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceeditorpluginmodel',
            name='name',
            field=models.CharField(blank=True, help_text='Name', max_length=32, null=True, verbose_name=b'Name'),
        ),
    ]
